# Generated by Django 3.1.1 on 2020-10-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_required_dmg'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='hp_lost',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
