# Generated by Django 3.1.1 on 2020-09-30 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dmg',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
