# Generated by Django 3.1.1 on 2020-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todolist_hp_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='hp',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
