# Generated by Django 3.1.1 on 2020-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201001_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
