# Generated by Django 3.1.1 on 2020-10-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todolist_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='actualDmg',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dmg',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='hp_lost',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='required_dmg',
        ),
    ]
