# Generated by Django 3.1.1 on 2020-10-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201003_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='hp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='hp_current',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='required_dmg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
