# Generated by Django 3.1.1 on 2020-09-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
