# Generated by Django 3.1.1 on 2020-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='actualDmg',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
