# Generated by Django 3.1.1 on 2020-10-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201003_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='actualDmg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='dmg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
